spring:
  application:
    name: config-service
  rabbitmq:
    addresses: localhost:5672
#  security:
#    user:
#      name: blog
#      password: blog
  cloud:
    config:
      server:
        git:
          uri: https://github.com/michaelilyin/blog-config.git
          clone-on-start: true

server:
  port: 8888

eureka:
  instance:
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: /actuator/info
    healthCheckUrlPath: /actuator/health
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/