version: '3'
services:
#  rabbitmq:
#    image: rabbitmq:3-management
#    ports:
#      - "5672:5672"
#      - "15672:15672"
#  webapp:
#    build:
#      context: .
#      args:
#        VERSION: 0.0.1-SNAPSHOT
#    environment:
#      PORT: 8081
#      DB_HOST: postgres
#      DB_PORT: 5432
#      AUTH_HOST: keycloak
#      DB_NAME: blog
#      DB_USER: demo
#      DB_PASSWORD: demo
#    ports:
#       - "8081:8081"

  postgres:
    build:
      context: ./postgres
    environment:
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo
    ports:
      - "5432:5432"