server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10

#logging:
#  level:
#    com.netflix: DEBUG
#    org.springframework: DEBUG
