server:
  port: 8081

#logging:
#  level:
#    com.netflix: DEBUG
#    org.springframework: DEBUG
#    org.springframework: INFO
#192.168.99.100
spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
  datasource-tech:
    url: ${JDBC_DATABASE_URL}?currentSchema=tech
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
  datasource-welcome:
    url: ${JDBC_DATABASE_URL}?currentSchema=welcome
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
  jpa:
    properties:
      hibernate.temp.use_jdbc_metadata_defaults: false