server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10

logging:
  level:
#    com.netflix: DEBUG
#    org.springframework: DEBUG
    org.springframework: INFO

michaelilyin:
  version: @project.version@
  build-time: @project.build.time@
